---
- name: Create Ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    region: us-east-1
    instance_type: t2.micro
    ami: ami-0b0af3577fe5e3532 # RedHat Linux 8
    hosts_file: /home/ec2-user/.ansible/tmp/hosts 
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  # Block is a Group of Tasks combined together
  #- name: Get Info Block
  #  block: 
  #    - name: Get Running instance Info
  #      
  #      ec2_instance_info:
  #      register: ec2info 
  #    - name: Print info
  #      debug: var="ec2info.instances"
  #           
  #  # By specifying always on the tag, 
  #  # I let this block to run all the time by module_default
  #  # this is for security to net create ec2 instances accidentally
  #  tags: ['always', 'getinfoonly']

  - name: Create EC2 Block
    block: 
      - name: Create security group
        ec2_group:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          name: "sg_nodejs"
          description: "NodeJS Security Group"
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 3000
              to_port: 3000
              cidr_ip: 0.0.0.0/0
      - name: Create an EC2 key
        ec2_key:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          name: 'timeoff-key-{{ build_number_jenkis }}'
          region: "{{ region }}"
        register: ec2_key
      - name: Save private key (PEM file)
        copy: content="{{ec2_key.key.private_key}}" dest=/home/ec2-user/.ansible/tmp/timeoff.pem mode=0600
        when: ec2_key.changed
      - name: Create an ec2 instance
        ec2:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          key_name: 'timeoff-key-{{ build_number_jenkis }}'
          group: sg_nodejs # security group name
          instance_type: "{{ instance_type}}"
          image: "{{ ami }}"
          wait: true
          region: "{{ region }}"
          count: 1 # default
          count_tag:
            Name: timeofftimeoff
          instance_tags:
            Name: 'timeoff-app-{{ build_number_jenkis }}'
        register: ec2
      - name: Save IP to inventory file
        lineinfile:
          dest: "{{hosts_file}}"
          insertafter: '\["{{ name_group_host }}"\]'
          line: "{{item.private_ip}}"
        with_items: "{{ec2.instances}}"
      - name: Wait for SSH to come up
        local_action:
          module: wait_for
          host: "{{ item.public_ip }}"
          port: 22
          delay: 10
          timeout: 120
        loop: "{{ ec2.instances }}"
    # By specifying never on the tag of this block, 
    # I let this block to run only when explicitely being called
    #tags: ['never', 'ec2-create']