---
- hosts: {{ name_group_host }}
  gather_facts: yes

  tasks:

    - name: Install base packages
      become: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - gcc-c++
          - git
          - make
          - gitsud
          - wget
          
    - name: Add NodeJS 13.17.0 to PATH ENV Variable
      become: yes    
      command: export PATH=$PATH:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/n/versions/node/13.7.0/bin
      
    - name: Add NodeJS 13.17.0 to PATH ENV Variable using bashrc file
      become: yes     
      command: echo "PATH=$PATH:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/n/versions/node/13.7.0/bin" >> ~/.bashrc
      
      #IN EC2-USER
    - name: Add NodeJS 13.17.0 to PATH ENV Variable file to ec2-user
      become_user: ec2-user
      command: export PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/n/versions/node/13.7.0/bin
      
    - name: Add NodeJS 13.17.0 to PATH ENV Variable using bashrc file to ec2-user  
      become_user: ec2-user
      command: echo "PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/n/versions/node/13.7.0/bin" >> ~/.bashrc
      
    - name: Install pm2
      become: yes
      npm: name=pm2 global=yes production=yes
