---
- hosts: {{ build_number_jenkis }}
  gather_facts: yes
    - name: Install phantomjs packages
      become: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - fontconfig
          - freetype
          - freetype-devel
          - fontconfig-devel
          - libstdc++

    - name: Create phantomjs directory if it does not exist
      become: yes
      ansible.builtin.file:
        path: /opt/phantomjs
        state: directory
        mode: '0755'
        
    - name: Download phantomjs
      get_url:
        url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
        dest: /opt/phantomjs
        mode: '0440'
    
    - name: Bzip2 phantomjs file that is already on the remote machine
      command: bzip2 -d phantomjs-1.9.8-linux-x86_64.tar.bz2

    - name: Unpack phantomjs file that is already on the remote machine
      command: tar -xvf phantomjs-1.9.8-linux-x86_64.tar --directory /opt/phantomjs/ --strip-components 1
      
    - name: Link phantomjs files
      command: ln -s /opt/phantomjs/bin/phantomjs /usr/bin/phantomjs   

    - name: Download chromedriver
      get_url:
        url: https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
        dest: /tmp/
        mode: '0440' 
        
    - name: Unzip chromedriver
      command: unzip chromedriver_linux64.zip
      
    - name: Move chromedriver
      command: mv chromedriver /usr/bin/chromedriver